import { memo, useState, type KeyboardEvent, type MouseEvent } from "react";
import { explorerStore, useExplorerSnapshot } from "./store";
import type { WorkspaceNode } from "./types";

function fileGlyph(name: string) { const ext = name.split('.').pop()?.toLowerCase(); return ({ ts: "TS", tsx: "⚛", js: "JS", jsx: "⚛", cs: "C#", json: "{}", md: "M↓", css: "#", html: "<>", py: "Py" } as Record<string, string>)[ext ?? ""] ?? "·"; }

interface TreeProps { onCreate: (type: "file" | "folder", parentId?: string) => void; onRename: (node: WorkspaceNode, name: string) => void; onDelete: (node: WorkspaceNode) => void; onMove: (nodeId: string, parentId?: string) => void; }

const TreeRow = memo(function TreeRow({ id, depth, actions }: { id: string; depth: number; actions: TreeProps }) {
  const state = useExplorerSnapshot(); const node = state.entities.get(id); const [menu, setMenu] = useState<{ x: number; y: number }>(); const [renaming, setRenaming] = useState(false); const [name, setName] = useState("");
  if (!node) return null; const folder = node.nodeType === "Folder"; const expanded = state.expanded.has(id); const children = state.children.get(id) ?? [];
  const context = (event: MouseEvent) => { event.preventDefault(); setMenu({ x: event.clientX, y: event.clientY }); };
  const keyboard = (event: KeyboardEvent) => { if (event.key === "Enter") folder ? explorerStore.toggle(id) : explorerStore.select(id); if (event.key === "ArrowRight" && folder && !expanded) explorerStore.toggle(id); if (event.key === "ArrowLeft" && folder && expanded) explorerStore.toggle(id); if (event.key === "F2") { setName(node.name); setRenaming(true); } if (event.key === "Delete") actions.onDelete(node); };
  return <><div className={`tree-row ${state.selectedId === id ? "selected" : ""}`} style={{ paddingLeft: `${depth * 14 + 8}px` }} tabIndex={0} role="treeitem" aria-expanded={folder ? expanded : undefined} draggable onDragStart={(event) => event.dataTransfer.setData("text/node-id", id)} onDragOver={(event) => { if (folder) event.preventDefault(); }} onDrop={(event) => { event.preventDefault(); actions.onMove(event.dataTransfer.getData("text/node-id"), folder ? id : node.parentId); }} onKeyDown={keyboard} onContextMenu={context} onClick={() => folder ? explorerStore.toggle(id) : explorerStore.select(id)}><span className="tree-chevron">{folder ? expanded ? "⌄" : "›" : ""}</span><span className={`node-glyph ${folder ? "folder" : "file"}`}>{folder ? expanded ? "▾" : "▸" : fileGlyph(node.name)}</span>{renaming ? <input className="inline-rename" value={name} autoFocus onChange={(e) => setName(e.target.value)} onBlur={() => setRenaming(false)} onClick={(e) => e.stopPropagation()} onKeyDown={(e) => { e.stopPropagation(); if (e.key === "Enter" && name.trim()) { actions.onRename(node, name); setRenaming(false); } if (e.key === "Escape") setRenaming(false); }} /> : <span>{node.name}</span>}</div>{folder && expanded && children.map((childId) => <TreeRow key={childId} id={childId} depth={depth + 1} actions={actions} />)}{menu && <div className="node-menu" style={{ left: menu.x, top: menu.y }} onMouseLeave={() => setMenu(undefined)}>{folder && <><button onClick={() => actions.onCreate("file", id)}>New file</button><button onClick={() => actions.onCreate("folder", id)}>New folder</button></>}<button onClick={() => { setName(node.name); setRenaming(true); setMenu(undefined); }}>Rename</button><button className="danger" onClick={() => { actions.onDelete(node); setMenu(undefined); }}>Delete</button></div>}</>;
});

export function FileTree(actions: TreeProps) { const state = useExplorerSnapshot(); const roots = state.children.get("root") ?? []; return <div className="file-tree" role="tree" aria-label="Project files" onDragOver={(event) => event.preventDefault()} onDrop={(event) => actions.onMove(event.dataTransfer.getData("text/node-id"), undefined)}>{roots.length ? roots.map((id) => <TreeRow key={id} id={id} depth={0} actions={actions} />) : <div className="tree-empty">No files yet</div>}</div>; }
