using System.Runtime.CompilerServices;
using Coding.Application.Features.AiAssistant;
using Microsoft.Extensions.Options;

namespace Coding.Infrastructure.AiAssistant;

public sealed class DevelopmentAiProvider(IOptions<AiOptions> options) : IAiProvider
{
    public async IAsyncEnumerable<AiStreamChunk> StreamAsync(AiRequest request, [EnumeratorCancellation] CancellationToken ct)
    {
        var contextSummary = string.IsNullOrWhiteSpace(request.RepositoryContext)
            ? "No repository context was supplied."
            : $"I received {request.RepositoryContext.Length:N0} characters of access-checked repository context.";
        var response = $"""
            Development provider response ({request.Action})

            {contextSummary}

            Your request was: {request.UserInstructions}

            This response is generated by the local fake provider configured as “{options.Value.Model}”.
            Configure a production IAiProvider implementation to receive model-generated analysis.
            """;
        var words = response.Split(' ');
        for (var i = 0; i < words.Length; i++)
        {
            ct.ThrowIfCancellationRequested();
            await Task.Delay(24, ct);
            yield return new AiStreamChunk(words[i] + (i == words.Length - 1 ? string.Empty : " "));
        }
        yield return new AiStreamChunk(string.Empty, true, Math.Max(1, (request.RepositoryContext.Length + request.UserInstructions.Length) / 4), Math.Max(1, response.Length / 4), "completed");
    }
}
