import { useEffect, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ConfirmDialog } from "../../components/ui/Dialog";
import { useToast } from "../../contexts/ToastContext";
import { aiApi } from "./api";
import type { AiAction, AiMessage } from "./types";

const actions: Array<{ value: AiAction; label: string }> = [{ value: "Explain", label: "Explain" }, { value: "SuggestFix", label: "Fix" }, { value: "Optimize", label: "Optimize" }, { value: "GenerateTests", label: "Generate tests" }];
const extractCode = (text: string) => /```[^\n]*\n([\s\S]*?)```/.exec(text)?.[1] ?? text;

export function AiAssistantPanel({ projectId, fileId, language, selectedCode, fileContent, onApply }: { projectId: string; fileId?: string; language?: string; selectedCode?: string; fileContent?: string; onApply: (content: string) => void }) {
  const [conversationId, setConversationId] = useState<string>(); const [messages, setMessages] = useState<AiMessage[]>([]); const [input, setInput] = useState(""); const [action, setAction] = useState<AiAction>("Chat"); const [streaming, setStreaming] = useState(""); const [isGenerating, setIsGenerating] = useState(false); const [applying, setApplying] = useState<string>(); const controller = useRef<AbortController | undefined>(undefined); const { show } = useToast(); const query = useQueryClient();
  const conversations = useQuery({ queryKey: ["ai-conversations", projectId], queryFn: () => aiApi.conversations(projectId), enabled: Boolean(projectId) });
  const detail = useQuery({ queryKey: ["ai-conversation", conversationId], queryFn: () => aiApi.conversation(conversationId!), enabled: Boolean(conversationId) });
  useEffect(() => { if (detail.data) setMessages(detail.data.messages); }, [detail.data]);
  useEffect(() => () => controller.current?.abort(), []);
  const send = async (selectedAction = action) => {
    const text = input.trim() || (selectedAction === "Chat" ? "" : `${selectedAction} the provided code.`); if (!text || controller.current) return;
    const localUser: AiMessage = { id: crypto.randomUUID(), role: "User", content: text, action: selectedAction, fileId, createdAt: new Date().toISOString() }; setMessages((old) => [...old, localUser]); setInput(""); setStreaming(""); setIsGenerating(true); const abort = new AbortController(); controller.current = abort; let responseText = ""; let activeConversationId = conversationId;
    try {
      await aiApi.stream({ projectId, userMessage: text, action: selectedAction, conversationId, currentFileId: fileId, selectedCode: selectedCode || undefined, neighboringCode: selectedCode ? undefined : fileContent?.slice(0, 6000), programmingLanguage: language }, abort.signal, (chunk) => { if (chunk.conversationId) { activeConversationId = chunk.conversationId; setConversationId(chunk.conversationId); } if (chunk.content) { responseText += chunk.content; setStreaming(responseText); } });
      await query.invalidateQueries({ queryKey: ["ai-conversations", projectId] });
      if (activeConversationId) { const saved = await aiApi.conversation(activeConversationId); setMessages(saved.messages); await query.invalidateQueries({ queryKey: ["ai-conversation", activeConversationId] }); }
    } catch (error) { if ((error as Error).name !== "AbortError") show(error instanceof Error ? error.message : "AI generation failed.", "error"); } finally { controller.current = undefined; setIsGenerating(false); setStreaming(""); }
  };
  const visible = streaming ? [...messages, { id: "stream", role: "Assistant" as const, content: streaming, action, createdAt: new Date().toISOString() }] : messages;
  return <div className="ai-panel"><header><div><strong>AI Assistant</strong><small>{selectedCode ? `${selectedCode.length} selected characters` : "Current file context"}</small></div><button onClick={() => { setConversationId(undefined); setMessages([]); }}>＋</button></header><select className="ai-conversation-select" value={conversationId ?? ""} onChange={(e) => setConversationId(e.target.value || undefined)}><option value="">New conversation</option>{conversations.data?.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><div className="ai-actions">{actions.map((item) => <button key={item.value} disabled={!fileId || isGenerating} onClick={() => { setAction(item.value); void send(item.value); }}>{item.label}</button>)}</div><div className="ai-messages">{visible.map((message) => <article key={message.id} className={message.role.toLowerCase()}><header><b>{message.role === "User" ? "You" : "Assistant"}</b>{message.role === "Assistant" && <span><button onClick={() => void navigator.clipboard.writeText(extractCode(message.content)).then(() => show("Copied to clipboard."))}>Copy</button><button onClick={() => setApplying(extractCode(message.content))}>Apply</button></span>}</header><pre>{message.content}</pre></article>)}{!visible.length && <div className="ai-empty"><b>How can I help?</b><p>Select code, choose an action, or ask a development question.</p></div>}</div><form className="ai-composer" onSubmit={(e) => { e.preventDefault(); void send(); }}><textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="Ask about your code…" /><div><select value={action} onChange={(e) => setAction(e.target.value as AiAction)}><option value="Chat">Chat</option><option value="FindBug">Find a bug</option><option value="Refactor">Refactor</option>{actions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select>{isGenerating ? <button type="button" className="stop" onClick={() => controller.current?.abort()}>Stop</button> : <button disabled={!input.trim()}>Send</button>}</div></form><ConfirmDialog open={Boolean(applying)} title="Apply AI suggestion?" description="This changes only the editor buffer. Review the diff and save manually when ready." confirmLabel="Apply to editor" onClose={() => setApplying(undefined)} onConfirm={() => { if (applying !== undefined) onApply(applying); setApplying(undefined); show("Suggestion applied to the editor buffer."); }} /></div>;
}
