import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { ConfirmDialog } from "../../components/ui/Dialog";
import { useToast } from "../../contexts/ToastContext";
import { kanbanApi } from "./api";
import { boardKey } from "./hooks";
import type { ProjectMember } from "../projects/types";
import type { ProjectTask } from "./types";

export function TaskDrawer({ task, members, canManage, onClose, onEdit }: { task?: ProjectTask; members: ProjectMember[]; canManage: boolean; onClose: () => void; onEdit: () => void }) {
  const [comment, setComment] = useState(""); const [confirmDelete, setConfirmDelete] = useState(false); const [busy, setBusy] = useState(false); const query = useQueryClient(); const { show } = useToast();
  if (!task) return null;
  const refresh = () => query.invalidateQueries({ queryKey: boardKey(task.projectId) });
  const act = async (operation: () => Promise<unknown>, message: string) => { setBusy(true); try { await operation(); await refresh(); show(message); } catch (e) { show(e instanceof Error ? e.message : "The operation failed.", "error"); } finally { setBusy(false); } };
  const assigned = new Set(task.assignees.map((x) => x.userId));
  return <><div className="task-drawer-backdrop" onMouseDown={onClose} /><aside className="task-drawer" aria-label="Task details"><header><div><span className={`priority-badge ${task.priority.toLowerCase()}`}>{task.priority}</span><h2>{task.title}</h2></div><button onClick={onClose} aria-label="Close">×</button></header><div className="task-drawer-body">{task.description && <section><h3>Description</h3><p>{task.description}</p></section>}<section><h3>Details</h3><dl><div><dt>Status</dt><dd>{task.status}</dd></div><div><dt>Due date</dt><dd>{task.dueDate ? new Date(task.dueDate).toLocaleDateString() : "No due date"}</dd></div></dl></section><section><h3>Assignees</h3><div className="assignee-list">{task.assignees.map((a) => <span key={a.userId}>{a.displayName}{canManage && <button disabled={busy} onClick={() => act(() => kanbanApi.unassign(task.id, a.userId), "Assignee removed.")}>×</button>}</span>)}</div>{canManage && <select value="" disabled={busy} onChange={(e) => e.target.value && act(() => kanbanApi.assign(task.id, e.target.value), "Member assigned.")}><option value="">Assign a member…</option>{members.filter((m) => !assigned.has(m.userId)).map((m) => <option key={m.userId} value={m.userId}>{m.fullName}</option>)}</select>}</section><section><h3>Comments</h3><div className="task-comments">{task.comments.map((item) => <article key={item.id}><strong>{item.displayName}</strong><time>{new Date(item.createdAt).toLocaleString()}</time><p>{item.content}</p></article>)}{!task.comments.length && <p className="muted">No comments yet.</p>}</div><form onSubmit={(e) => { e.preventDefault(); if (!comment.trim()) return; void act(() => kanbanApi.comment(task.id, comment.trim()), "Comment added.").then(() => setComment("")); }}><textarea value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Write a comment. Use @username to mention someone." /><button className="ui-button primary" disabled={busy || !comment.trim()}>Add comment</button></form></section></div>{canManage && <footer><button className="ui-button ghost" onClick={onEdit}>Edit task</button><button className="ui-button danger" onClick={() => setConfirmDelete(true)}>Delete task</button></footer>}</aside><ConfirmDialog open={confirmDelete} title="Delete task?" description="This task will be removed from the board." confirmLabel="Delete task" destructive pending={busy} onClose={() => setConfirmDelete(false)} onConfirm={() => void act(() => kanbanApi.remove(task.id), "Task deleted.").then(onClose)} /></>;
}
