import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { EmptyState, ErrorState, LoadingState } from "../components/AsyncState";
import { activityApi, type ActivityFilters } from "../features/activities/api";

export function AdminActivityPage() {
  const [filters, setFilters] = useState<ActivityFilters>({ page: 1 }); const logs = useQuery({ queryKey: ["admin", "activities", filters], queryFn: () => activityApi.list(filters) });
  const update = (key: keyof ActivityFilters, value: string) => setFilters((old) => ({ ...old, [key]: value || undefined, page: 1 }));
  return <main className="dashboard-content activity-page"><header className="feature-heading"><div><p className="dashboard-date">ADMIN AUDIT</p><h1>Activity log</h1><p>Review security and workspace events without exposing sensitive data.</p></div></header><section className="activity-filters"><input placeholder="User ID" onChange={(e) => update("userId", e.target.value)} /><input placeholder="Project ID" onChange={(e) => update("projectId", e.target.value)} /><input placeholder="Action type" onChange={(e) => update("actionType", e.target.value)} /><input placeholder="Entity type" onChange={(e) => update("entityType", e.target.value)} /><input type="date" aria-label="From date" onChange={(e) => update("from", e.target.value)} /><input type="date" aria-label="To date" onChange={(e) => update("to", e.target.value)} /></section>{logs.isLoading ? <LoadingState label="Loading activity…" /> : logs.isError ? <ErrorState message={logs.error.message} retry={() => logs.refetch()} /> : !logs.data?.items.length ? <EmptyState title="No matching activity" description="Try changing the filters or date range." /> : <><section className="activity-table-wrap"><table className="activity-table"><thead><tr><th>When</th><th>User</th><th>Project</th><th>Action</th><th>Entity</th><th>Description</th><th>IP</th></tr></thead><tbody>{logs.data.items.map((item) => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.userName ?? item.userId ?? "System"}</td><td>{item.projectName ?? item.projectId ?? "—"}</td><td><span>{item.actionType}</span></td><td>{item.entityType}</td><td>{item.description}</td><td>{item.ipAddress ?? "—"}</td></tr>)}</tbody></table></section><div className="activity-pagination"><button disabled={logs.data.page <= 1} onClick={() => setFilters((x) => ({ ...x, page: (x.page ?? 1) - 1 }))}>Previous</button><span>Page {logs.data.page} · {logs.data.total} events</span><button disabled={logs.data.page * logs.data.pageSize >= logs.data.total} onClick={() => setFilters((x) => ({ ...x, page: (x.page ?? 1) + 1 }))}>Next</button></div></>}</main>;
}
