import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { ConfirmDialog, Dialog } from "../components/ui/Dialog";
import { useToast } from "../contexts/ToastContext";
import { fileExplorerApi } from "../features/fileExplorer/api";
import { FileTree } from "../features/fileExplorer/FileTree";
import { explorerStore, useExplorerSnapshot } from "../features/fileExplorer/store";
import type { WorkspaceNode } from "../features/fileExplorer/types";
import { VersionHistory } from "../features/fileExplorer/VersionHistory";

export function FileExplorerPage() {
  const { projectId = "" } = useParams(); const navigate = useNavigate(); const { show } = useToast(); const state = useExplorerSnapshot(); const selected = state.selectedId ? state.entities.get(state.selectedId) : undefined;
  const tree = useQuery({ queryKey: ["file-tree", projectId], queryFn: () => fileExplorerApi.tree(projectId), enabled: Boolean(projectId) });
  const file = useQuery({ queryKey: ["file-content", selected?.id], queryFn: () => fileExplorerApi.content(selected!.id), enabled: selected?.nodeType === "File" });
  const [draft, setDraft] = useState(""); const [saveState, setSaveState] = useState("Saved"); const [create, setCreate] = useState<{ type: "file" | "folder"; parentId?: string }>(); const [newName, setNewName] = useState(""); const [deleting, setDeleting] = useState<WorkspaceNode>(); const [historyKey, setHistoryKey] = useState(0); const initialized = useRef<string | undefined>(undefined);
  useEffect(() => { if (tree.data) explorerStore.load(tree.data); }, [tree.data]);
  useEffect(() => { if (file.data && initialized.current !== file.data.nodeId + file.data.contentHash) { initialized.current = file.data.nodeId + file.data.contentHash; setDraft(file.data.content); setSaveState("Saved"); } }, [file.data]);
  useEffect(() => { if (!file.data || draft === file.data.content) return; setSaveState("Unsaved"); const timeout = window.setTimeout(async () => { try { setSaveState("Saving…"); const result = await fileExplorerApi.save(file.data.nodeId, draft); initialized.current = result.nodeId + result.contentHash; setSaveState(`Saved · v${result.versionNumber}`); setHistoryKey((key) => key + 1); } catch (error) { setSaveState("Save failed"); show(error instanceof Error ? error.message : "Save failed.", "error"); } }, 1200); return () => window.clearTimeout(timeout); }, [draft, file.data, show]);
  const reload = async () => { const result = await tree.refetch(); if (result.data) explorerStore.load(result.data); };
  const performCreate = async () => { if (!create || !newName.trim()) return; try { create.type === "file" ? await fileExplorerApi.createFile(projectId, create.parentId, newName) : await fileExplorerApi.createFolder(projectId, create.parentId, newName); setCreate(undefined); setNewName(""); await reload(); show(`${create.type === "file" ? "File" : "Folder"} created.`); } catch (error) { show(error instanceof Error ? error.message : "Creation failed.", "error"); } };
  const actions = { onCreate: (type: "file" | "folder", parentId?: string) => { setCreate({ type, parentId }); setNewName(""); }, onRename: async (node: WorkspaceNode, name: string) => { try { await fileExplorerApi.rename(node.id, name); await reload(); } catch (error) { show(error instanceof Error ? error.message : "Rename failed.", "error"); } }, onDelete: setDeleting, onMove: async (nodeId: string, parentId?: string) => { if (!nodeId) return; try { await fileExplorerApi.move(nodeId, parentId); await reload(); } catch (error) { show(error instanceof Error ? error.message : "Move failed.", "error"); } } };
  return <main className="workspace-page"><header className="workspace-toolbar"><button onClick={() => navigate(`/projects/${projectId}/settings`)}>← Project</button><strong>File Explorer</strong><div><button onClick={() => actions.onCreate("file", selected?.nodeType === "Folder" ? selected.id : selected?.parentId)}>＋ File</button><button onClick={() => actions.onCreate("folder", selected?.nodeType === "Folder" ? selected.id : selected?.parentId)}>＋ Folder</button></div></header><div className="workspace-grid"><aside className="explorer-panel"><header><span>EXPLORER</span><button onClick={() => reload()}>↻</button></header>{tree.isLoading ? <div className="tree-empty">Loading files…</div> : <FileTree {...actions} />}</aside><section className="editor-panel">{selected?.nodeType === "File" ? <>{file.isLoading ? <div className="editor-empty">Loading content…</div> : <><header className="editor-tab"><span>{selected.name}</span><small>{file.data?.path}</small><em>{saveState}</em></header><textarea className="code-editor" value={draft} onChange={(event) => setDraft(event.target.value)} spellCheck={false} aria-label={`Edit ${selected.name}`} /></>}</> : <div className="editor-empty"><span className="brand-mark">C</span><h2>Select a file to begin</h2><p>Choose a file in the explorer or create a new one.</p></div>}</section>{selected?.nodeType === "File" && <VersionHistory nodeId={selected.id} refreshKey={historyKey} onRestore={async () => { await file.refetch(); setHistoryKey((key) => key + 1); show("Version restored."); }} />}</div><Dialog open={Boolean(create)} title={`New ${create?.type ?? "node"}`} description="Names are validated and paths are generated by the server." onClose={() => setCreate(undefined)} footer={<><button className="ui-button ghost" onClick={() => setCreate(undefined)}>Cancel</button><button className="ui-button primary" onClick={performCreate}>Create</button></>}><div className="feature-form"><label>Name<input autoFocus value={newName} onChange={(event) => setNewName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") performCreate(); }} placeholder={create?.type === "file" ? "index.ts" : "src"} /></label></div></Dialog><ConfirmDialog open={Boolean(deleting)} title={`Delete ${deleting?.name ?? "node"}?`} description={deleting?.nodeType === "Folder" ? "This folder and every descendant will be soft-deleted." : "The file and its version history will be hidden."} destructive confirmLabel="Delete" onClose={() => setDeleting(undefined)} onConfirm={async () => { if (!deleting) return; try { await fileExplorerApi.remove(deleting.id); if (state.selectedId === deleting.id) explorerStore.select(""); setDeleting(undefined); await reload(); show("Node deleted."); } catch (error) { show(error instanceof Error ? error.message : "Delete failed.", "error"); } }} /></main>;
}
