import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useToast } from "../contexts/ToastContext";
import { useAuth } from "../hooks/useAuth";
import { useTheme } from "../hooks/useTheme";

interface Preferences { compactMode: boolean; reducedMotion: boolean; desktopNotifications: boolean; emailSummaries: boolean; }
const defaults: Preferences = { compactMode: false, reducedMotion: false, desktopNotifications: true, emailSummaries: false };
const load = () => { try { return { ...defaults, ...JSON.parse(localStorage.getItem("coding-preferences") ?? "{}") as Partial<Preferences> }; } catch { return defaults; } };

export function SettingsPage() {
  const { session, logout } = useAuth(); const { theme, toggleTheme } = useTheme(); const navigate = useNavigate(); const { show } = useToast(); const [preferences, setPreferences] = useState(load);
  useEffect(() => { document.documentElement.dataset.compact = String(preferences.compactMode); document.documentElement.dataset.reducedMotion = String(preferences.reducedMotion); localStorage.setItem("coding-preferences", JSON.stringify(preferences)); }, [preferences]);
  const toggle = (key: keyof Preferences) => setPreferences((current) => ({ ...current, [key]: !current[key] }));
  const user = session!.user;
  return <main className="dashboard-content feature-page"><header className="feature-heading"><div><p className="dashboard-date">YOUR ACCOUNT</p><h1>Settings</h1><p>Manage appearance, notifications, security, and workspace preferences.</p></div></header><div className="settings-layout"><section className="settings-main"><article className="settings-card"><header><div><h2>Profile</h2><p>Identity associated with your authenticated session.</p></div><span className="role-badge admin">{user.roles.join(", ")}</span></header><dl><div><dt>Full name</dt><dd>{user.firstName} {user.lastName}</dd></div><div><dt>Username</dt><dd>@{user.userName}</dd></div><div><dt>Email address</dt><dd>{user.email}</dd></div><div><dt>Email status</dt><dd>{user.isEmailVerified ? "Verified" : "Verification pending"}</dd></div></dl></article><article className="settings-card"><header><div><h2>Appearance</h2><p>Preferences are saved in this browser.</p></div></header><div className="preference-list"><label><span><b>Dark appearance</b><small>Use the dark workspace color scheme.</small></span><input type="checkbox" checked={theme === "dark"} onChange={toggleTheme} /></label><label><span><b>Compact mode</b><small>Reduce navigation and card spacing.</small></span><input type="checkbox" checked={preferences.compactMode} onChange={() => toggle("compactMode")} /></label><label><span><b>Reduced motion</b><small>Disable non-essential transitions and animations.</small></span><input type="checkbox" checked={preferences.reducedMotion} onChange={() => toggle("reducedMotion")} /></label></div></article><article className="settings-card"><header><div><h2>Notifications</h2><p>Choose how this browser presents workspace updates.</p></div></header><div className="preference-list"><label><span><b>Desktop notifications</b><small>Show supported browser alerts for important events.</small></span><input type="checkbox" checked={preferences.desktopNotifications} onChange={() => toggle("desktopNotifications")} /></label><label><span><b>Email summaries</b><small>Prepare a preference for periodic activity summaries.</small></span><input type="checkbox" checked={preferences.emailSummaries} onChange={() => toggle("emailSummaries")} /></label></div></article></section><aside className="settings-side"><article className="danger-card"><h2>Security</h2><p>Sessions use short-lived JWT access tokens and secure refresh cookies.</p><button className="ui-button ghost" onClick={() => navigate("/help?topic=security")}>Security help</button></article><article className="danger-card"><h2>Sign out</h2><p>End this browser session and disconnect real-time services.</p><button className="ui-button danger" onClick={() => void logout().then(() => { show("Signed out."); navigate("/login"); })}>Sign out</button></article></aside></div></main>;
}
