import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ErrorState, LoadingState } from "../components/AsyncState";
import { settingsApi, type Preference } from "../features/settings/api";
import { useToast } from "../contexts/ToastContext";

const profileSchema=z.object({firstName:z.string().min(1).max(80),lastName:z.string().min(1).max(80),bio:z.string().max(500).optional()});
const passwordSchema=z.object({currentPassword:z.string().min(1),newPassword:z.string().min(10).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/).regex(/[^a-zA-Z0-9]/),confirmPassword:z.string(),revokeOtherSessions:z.boolean()}).refine(x=>x.newPassword===x.confirmPassword,{path:["confirmPassword"],message:"Passwords do not match."});
type ProfileForm=z.infer<typeof profileSchema>;type PasswordForm=z.infer<typeof passwordSchema>;
export function SettingsPage(){
 const [section,setSection]=useState("profile"),qc=useQueryClient(),{show}=useToast(),settings=useQuery({queryKey:["settings"],queryFn:settingsApi.get}),sessions=useQuery({queryKey:["settings","sessions"],queryFn:settingsApi.sessions,enabled:section==="security"});
 const profile=useForm<ProfileForm>({resolver:zodResolver(profileSchema),values:settings.data?{firstName:settings.data.profile.firstName,lastName:settings.data.profile.lastName,bio:settings.data.profile.bio??""}:undefined});
 const password=useForm<PasswordForm>({resolver:zodResolver(passwordSchema),defaultValues:{currentPassword:"",newPassword:"",confirmPassword:"",revokeOtherSessions:true}});
 const saveProfile=useMutation({mutationFn:settingsApi.profile,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Profile updated.")},onError:e=>show(e.message,"error")});
 const savePassword=useMutation({mutationFn:(v:PasswordForm)=>settingsApi.password(v),onSuccess:()=>{password.reset();show("Password changed.")},onError:e=>show(e.message,"error")});
 const savePrefs=useMutation({mutationFn:settingsApi.preferences,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Preferences saved.")}});
 const saveNotifications=useMutation({mutationFn:settingsApi.notifications,onSuccess:()=>show("Notification preferences saved.")});
 const avatar=useMutation({mutationFn:settingsApi.avatar,onSuccess:()=>{void qc.invalidateQueries({queryKey:["settings"]});show("Avatar updated.")},onError:e=>show(e.message,"error")});
 const revoke=useMutation({mutationFn:settingsApi.revoke,onSuccess:()=>{void sessions.refetch();show("Session revoked.")}});
 if(settings.isLoading)return <main className="settings-page"><LoadingState label="Loading account settings…"/></main>;if(settings.isError)return <main className="settings-page"><ErrorState message={settings.error.message} retry={()=>settings.refetch()}/></main>;const data=settings.data!;
 const updatePreference=(key:keyof Preference,value:string|boolean)=>savePrefs.mutate({...data.preferences,[key]:value});
 return <main className="settings-page"><header><p>ACCOUNT CENTER</p><h1>Settings</h1><span>Manage your identity, experience, notifications, and security.</span></header><div className="settings-console"><nav>{[["profile","Profile"],["appearance","Appearance"],["notifications","Notifications"],["security","Security"]].map(([id,label])=><button className={section===id?"active":""} onClick={()=>setSection(id)} key={id}>{label}</button>)}</nav><section className="settings-content">
 {section==="profile"&&<><div className="settings-section-heading"><div><h2>Profile information</h2><p>Update your public identity and biography.</p></div><label className="avatar-upload">{data.profile.avatarUrl?<img src={data.profile.avatarUrl}/>:<span>{data.profile.firstName[0]}</span>}<input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>e.target.files?.[0]&&avatar.mutate(e.target.files[0])}/><small>Change avatar</small></label></div><form className="settings-form" onSubmit={profile.handleSubmit(v=>saveProfile.mutate(v))}><div className="form-row"><label>First name<input {...profile.register("firstName")}/><small>{profile.formState.errors.firstName?.message}</small></label><label>Last name<input {...profile.register("lastName")}/></label></div><label>Username<input value={data.profile.userName} disabled/></label><label>Email<input value={data.profile.email} disabled/></label><label>Biography<textarea rows={5} {...profile.register("bio")}/><small>{profile.formState.errors.bio?.message}</small></label><button className="ui-button primary">Save profile</button></form></>}
 {section==="appearance"&&<><SettingsTitle title="Appearance and language" copy="Preferences follow your account across devices."/><div className="settings-options"><label><span><b>Theme</b><small>Choose your preferred color scheme.</small></span><select value={data.preferences.theme} onChange={e=>updatePreference("theme",e.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span><b>Language</b><small>Interface language preference.</small></span><select value={data.preferences.language} onChange={e=>updatePreference("language",e.target.value)}><option value="en">English</option><option value="az">Azərbaycan</option><option value="tr">Türkçe</option></select></label>{(["compactMode","reducedMotion","securityAlertsEnabled"] as const).map(key=><label key={key}><span><b>{key.replace(/([A-Z])/g," $1")}</b><small>Saved securely to your account.</small></span><input type="checkbox" checked={data.preferences[key]} onChange={e=>updatePreference(key,e.target.checked)}/></label>)}</div></>}
 {section==="notifications"&&<><SettingsTitle title="Notification preferences" copy="Control in-app and email delivery by event type."/><div className="notification-settings"><header><span>Event</span><span>In app</span><span>Email</span></header>{data.notifications.map((item,index)=><div key={item.type}><b>{item.type.replace(/([A-Z])/g," $1")}</b><input type="checkbox" checked={item.inAppEnabled} onChange={e=>{const next=[...data.notifications];next[index]={...item,inAppEnabled:e.target.checked};saveNotifications.mutate(next)}}/><input type="checkbox" checked={item.emailEnabled} onChange={e=>{const next=[...data.notifications];next[index]={...item,emailEnabled:e.target.checked};saveNotifications.mutate(next)}}/></div>)}</div></>}
 {section==="security"&&<><SettingsTitle title="Password and sessions" copy="Review devices and strengthen account access."/><form className="settings-form password-form" onSubmit={password.handleSubmit(v=>savePassword.mutate(v))}><label>Current password<input type="password" {...password.register("currentPassword")}/></label><div className="form-row"><label>New password<input type="password" {...password.register("newPassword")}/><small>{password.formState.errors.newPassword?.message}</small></label><label>Confirm password<input type="password" {...password.register("confirmPassword")}/><small>{password.formState.errors.confirmPassword?.message}</small></label></div><label className="check-row"><input type="checkbox" {...password.register("revokeOtherSessions")}/> Revoke other sessions after changing password</label><button className="ui-button primary">Change password</button></form><div className="session-list"><h3>Active sessions</h3>{sessions.isLoading?<LoadingState label="Loading sessions…"/>:sessions.data?.map(item=><article key={item.id}><span>◉</span><div><b>{item.device}</b><small>{item.ipAddress??"Unknown IP"} · Active {new Date(item.lastSeenAt).toLocaleString()}</small></div><button onClick={()=>revoke.mutate(item.id)}>Revoke</button></article>)}</div></>}
 </section></div></main>
}
function SettingsTitle({title,copy}:{title:string;copy:string}){return <div className="settings-section-heading"><div><h2>{title}</h2><p>{copy}</p></div></div>}
