import { createContext, useCallback, useEffect, useMemo, useState, type PropsWithChildren } from "react";
export type Language = "en" | "az" | "ru" | "de" | "tr";
export const languages: Array<{ code: Language; label: string; nativeLabel: string }> = [
  { code:"en",label:"English",nativeLabel:"English" },{ code:"az",label:"Azerbaijani",nativeLabel:"Azərbaycan dili" },
  { code:"ru",label:"Russian",nativeLabel:"Русский" },{ code:"de",label:"German",nativeLabel:"Deutsch" },{ code:"tr",label:"Turkish",nativeLabel:"Türkçe" },
];
const en = {
  workspace:"Workspace",overview:"Overview",projects:"Projects",chat:"Chat",team:"Team",analytics:"Analytics",admin:"Admin",activity:"Activity",manage:"Manage",settings:"Settings",help:"Help center",search:"Search projects, files, users and tasks…",newProject:"New project",openNavigation:"Open navigation",closeNavigation:"Close navigation",theme:"Change theme",language:"Language",appearance:"Appearance",notifications:"Notifications",security:"Security",profile:"Profile",
  accountCenter:"Account center",settingsIntro:"Manage your identity, experience, notifications, and security.",profileInfo:"Profile information",profileCopy:"Update your public identity and biography.",changeAvatar:"Change avatar",firstName:"First name",lastName:"Last name",username:"Username",email:"Email",biography:"Biography",saveProfile:"Save profile",appearanceLanguage:"Appearance and language",appearanceCopy:"Preferences follow your account across devices.",themeLabel:"Theme",themeCopy:"Choose your preferred color scheme.",languageCopy:"Changes are applied immediately and saved to your account.",system:"System",light:"Light",dark:"Dark",compactMode:"Compact mode",reducedMotion:"Reduced motion",securityAlerts:"Security alerts enabled",savedAccount:"Saved securely to your account.",notificationPrefs:"Notification preferences",notificationCopy:"Control in-app and email delivery by event type.",event:"Event",inApp:"In app",passwordSessions:"Password and sessions",passwordCopy:"Review devices and strengthen account access.",currentPassword:"Current password",newPassword:"New password",confirmPassword:"Confirm password",revokeOthers:"Revoke other sessions after changing password",changePassword:"Change password",activeSessions:"Active sessions",currentSession:"Current session",unknownIp:"Unknown IP",revoke:"Revoke",loadingSettings:"Loading account settings…",
} as const;
export type TranslationKey = keyof typeof en;
const overrides: Record<Exclude<Language,"en">,Partial<Record<TranslationKey,string>>> = {
  az:{workspace:"İş sahəsi",overview:"Ümumi baxış",projects:"Layihələr",chat:"Söhbət",team:"Komanda",analytics:"Analitika",admin:"İdarəetmə",activity:"Fəaliyyət",manage:"Tənzimləmələr",settings:"Parametrlər",help:"Yardım mərkəzi",search:"Layihə, fayl, istifadəçi və tapşırıqlarda axtar…",newProject:"Yeni layihə",openNavigation:"Naviqasiyanı aç",closeNavigation:"Naviqasiyanı bağla",theme:"Mövzunu dəyiş",language:"Dil",appearance:"Görünüş",notifications:"Bildirişlər",security:"Təhlükəsizlik",profile:"Profil",settingsIntro:"Şəxsiyyətinizi, görünüşü, bildirişləri və təhlükəsizliyi idarə edin.",profileInfo:"Profil məlumatları",profileCopy:"İctimai adınızı və bioqrafiyanızı yeniləyin.",changeAvatar:"Avatarı dəyiş",firstName:"Ad",lastName:"Soyad",username:"İstifadəçi adı",email:"E-poçt",biography:"Bioqrafiya",saveProfile:"Profili saxla",appearanceLanguage:"Görünüş və dil",appearanceCopy:"Seçimlər bütün cihazlarda hesabınıza tətbiq olunur.",themeLabel:"Mövzu",themeCopy:"İstədiyiniz rəng sxemini seçin.",languageCopy:"Dəyişiklik dərhal tətbiq edilir və hesabda saxlanılır.",system:"Sistem",light:"Açıq",dark:"Tünd",compactMode:"Kompakt rejim",reducedMotion:"Azaldılmış hərəkət",securityAlerts:"Təhlükəsizlik xəbərdarlıqları",savedAccount:"Hesabınızda təhlükəsiz saxlanılır.",notificationPrefs:"Bildiriş seçimləri",notificationCopy:"Hadisə növünə görə tətbiq və e-poçt bildirişlərini idarə edin.",event:"Hadisə",inApp:"Tətbiqdə",passwordSessions:"Şifrə və sessiyalar",passwordCopy:"Cihazları yoxlayın və hesab təhlükəsizliyini gücləndirin.",currentPassword:"Cari şifrə",newPassword:"Yeni şifrə",confirmPassword:"Şifrəni təsdiqlə",revokeOthers:"Şifrə dəyişəndə digər sessiyaları ləğv et",changePassword:"Şifrəni dəyiş",activeSessions:"Aktiv sessiyalar",revoke:"Ləğv et",loadingSettings:"Hesab parametrləri yüklənir…"},
  ru:{workspace:"Рабочее пространство",overview:"Обзор",projects:"Проекты",chat:"Чат",team:"Команда",analytics:"Аналитика",admin:"Администрирование",activity:"Активность",manage:"Управление",settings:"Настройки",help:"Центр помощи",search:"Поиск проектов, файлов, пользователей и задач…",newProject:"Новый проект",openNavigation:"Открыть навигацию",closeNavigation:"Закрыть навигацию",theme:"Изменить тему",language:"Язык",appearance:"Внешний вид",notifications:"Уведомления",security:"Безопасность",profile:"Профиль",settingsIntro:"Управляйте профилем, интерфейсом, уведомлениями и безопасностью.",profileInfo:"Информация профиля",profileCopy:"Обновите публичное имя и биографию.",changeAvatar:"Изменить аватар",firstName:"Имя",lastName:"Фамилия",username:"Имя пользователя",email:"Эл. почта",biography:"Биография",saveProfile:"Сохранить профиль",appearanceLanguage:"Внешний вид и язык",appearanceCopy:"Настройки синхронизируются между устройствами.",themeLabel:"Тема",themeCopy:"Выберите цветовую схему.",languageCopy:"Изменения применяются сразу и сохраняются в аккаунте.",system:"Системная",light:"Светлая",dark:"Тёмная",compactMode:"Компактный режим",reducedMotion:"Уменьшение анимации",securityAlerts:"Оповещения безопасности",savedAccount:"Безопасно сохранено в аккаунте.",notificationPrefs:"Настройки уведомлений",notificationCopy:"Настройте уведомления в приложении и по почте.",event:"Событие",inApp:"В приложении",passwordSessions:"Пароль и сеансы",passwordCopy:"Проверьте устройства и защитите аккаунт.",currentPassword:"Текущий пароль",newPassword:"Новый пароль",confirmPassword:"Подтвердите пароль",revokeOthers:"Завершить другие сеансы после смены пароля",changePassword:"Изменить пароль",activeSessions:"Активные сеансы",revoke:"Завершить",loadingSettings:"Загрузка настроек аккаунта…"},
  de:{workspace:"Arbeitsbereich",overview:"Übersicht",projects:"Projekte",chat:"Chat",team:"Team",analytics:"Analysen",admin:"Administration",activity:"Aktivität",manage:"Verwalten",settings:"Einstellungen",help:"Hilfezentrum",search:"Projekte, Dateien, Benutzer und Aufgaben durchsuchen…",newProject:"Neues Projekt",openNavigation:"Navigation öffnen",closeNavigation:"Navigation schließen",theme:"Design ändern",language:"Sprache",appearance:"Darstellung",notifications:"Benachrichtigungen",security:"Sicherheit",profile:"Profil",settingsIntro:"Verwalten Sie Identität, Darstellung, Benachrichtigungen und Sicherheit.",profileInfo:"Profilinformationen",profileCopy:"Aktualisieren Sie Ihren öffentlichen Namen und Ihre Biografie.",changeAvatar:"Avatar ändern",firstName:"Vorname",lastName:"Nachname",username:"Benutzername",email:"E-Mail",biography:"Biografie",saveProfile:"Profil speichern",appearanceLanguage:"Darstellung und Sprache",appearanceCopy:"Einstellungen gelten auf allen Geräten.",themeLabel:"Design",themeCopy:"Wählen Sie Ihr Farbschema.",languageCopy:"Änderungen werden sofort angewendet und gespeichert.",system:"System",light:"Hell",dark:"Dunkel",compactMode:"Kompaktmodus",reducedMotion:"Reduzierte Bewegung",securityAlerts:"Sicherheitswarnungen",savedAccount:"Sicher im Konto gespeichert.",notificationPrefs:"Benachrichtigungseinstellungen",notificationCopy:"Steuern Sie App- und E-Mail-Benachrichtigungen.",event:"Ereignis",inApp:"In der App",passwordSessions:"Passwort und Sitzungen",passwordCopy:"Prüfen Sie Geräte und schützen Sie Ihr Konto.",currentPassword:"Aktuelles Passwort",newPassword:"Neues Passwort",confirmPassword:"Passwort bestätigen",revokeOthers:"Andere Sitzungen nach Passwortänderung beenden",changePassword:"Passwort ändern",activeSessions:"Aktive Sitzungen",revoke:"Beenden",loadingSettings:"Kontoeinstellungen werden geladen…"},
  tr:{workspace:"Çalışma alanı",overview:"Genel bakış",projects:"Projeler",chat:"Sohbet",team:"Ekip",analytics:"Analizler",admin:"Yönetim",activity:"Etkinlik",manage:"Yönet",settings:"Ayarlar",help:"Yardım merkezi",search:"Proje, dosya, kullanıcı ve görevlerde ara…",newProject:"Yeni proje",openNavigation:"Navigasyonu aç",closeNavigation:"Navigasyonu kapat",theme:"Temayı değiştir",language:"Dil",appearance:"Görünüm",notifications:"Bildirimler",security:"Güvenlik",profile:"Profil",settingsIntro:"Kimliğinizi, görünümü, bildirimleri ve güvenliği yönetin.",profileInfo:"Profil bilgileri",profileCopy:"Herkese açık adınızı ve biyografinizi güncelleyin.",changeAvatar:"Avatarı değiştir",firstName:"Ad",lastName:"Soyad",username:"Kullanıcı adı",email:"E-posta",biography:"Biyografi",saveProfile:"Profili kaydet",appearanceLanguage:"Görünüm ve dil",appearanceCopy:"Tercihler hesabınızla cihazlar arasında eşitlenir.",themeLabel:"Tema",themeCopy:"Tercih ettiğiniz renk şemasını seçin.",languageCopy:"Değişiklikler hemen uygulanır ve hesabınıza kaydedilir.",system:"Sistem",light:"Açık",dark:"Koyu",compactMode:"Kompakt mod",reducedMotion:"Azaltılmış hareket",securityAlerts:"Güvenlik uyarıları",savedAccount:"Hesabınızda güvenle saklanır.",notificationPrefs:"Bildirim tercihleri",notificationCopy:"Uygulama ve e-posta bildirimlerini yönetin.",event:"Etkinlik",inApp:"Uygulamada",passwordSessions:"Şifre ve oturumlar",passwordCopy:"Cihazları inceleyin ve hesabınızı güçlendirin.",currentPassword:"Mevcut şifre",newPassword:"Yeni şifre",confirmPassword:"Şifreyi doğrula",revokeOthers:"Şifre değişince diğer oturumları kapat",changePassword:"Şifreyi değiştir",activeSessions:"Aktif oturumlar",revoke:"İptal et",loadingSettings:"Hesap ayarları yükleniyor…"},
};
interface Value{language:Language;setLanguage:(language:Language)=>void;t:(key:TranslationKey)=>string}
export const LanguageContext=createContext<Value|null>(null);
const initial=():Language=>{const value=localStorage.getItem("coding-language");return languages.some(x=>x.code===value)?value as Language:"en"};
export function LanguageProvider({children}:PropsWithChildren){const[language,setState]=useState<Language>(initial);useEffect(()=>{document.documentElement.lang=language;localStorage.setItem("coding-language",language)},[language]);const setLanguage=useCallback((value:Language)=>setState(value),[]);const t=useCallback((key:TranslationKey)=>language==="en"?en[key]:overrides[language][key]??en[key],[language]);const value=useMemo(()=>({language,setLanguage,t}),[language,setLanguage,t]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
